core/src/com/eric/mtd/game/ui/view/OptionsGroup.java

Fixed bug where the Main Menu and New Game buttons resumed the game.

MTD - 9 - Fixed Options View Bug

---

core/src/com/eric/mtd/game/helper/CollisionDetection.java
core/src/com/eric/mtd/game/model/actor/GameActor.java
core/src/com/eric/mtd/game/model/actor/tower/Tower.java
core/src/com/eric/mtd/game/model/actor/tower/TowerTank.java
core/src/com/eric/mtd/game/model/actor/tower/TowerTurret.java
core/src/com/eric/mtd/levelselect/LevelSelectStage.java

Changed Turret Range to be a triangle shape. getRangeShape now returns Shape2D instead of Circle.

MTD-10 Changes to Turret Range Shape

---

core/src/com/eric/mtd/game/GameScreen.java
core/src/com/eric/mtd/screen/AbstractScreen.java

Added Logic in Game Screen Class that checks for the options window

MTD-19-Fixed

---

core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemyFlameThrower.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerTurret.java

Turret Range now increases with Range change

MTD-22- Fixed Turret Range

---

android/assets/game/levels/level2/waves/wave1.json
android/assets/game/levels/level2/waves/wave2.json
core/src/com/eric/mtd/game/model/actor/combat/tower/Tower.java

MTD-23-Fixed attack speed

---

core/src/com/eric/mtd/game/GameScreen.java
core/src/com/eric/mtd/menu/MenuScreen.java
core/src/com/eric/mtd/util/AudioUtil.java
core/src/com/eric/mtd/util/Logger.java

MTD-32-Fixed Audio Issue

---

android/assets/game/levels/level2/waves/wave1.json
core/src/com/eric/mtd/game/model/actor/combat/enemy/Enemy.java
core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemyFlameThrower.java
core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemyMachineGun.java
core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemyRifle.java
core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemyRocketLauncher.java
core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemySniper.java
core/src/com/eric/mtd/game/model/actor/combat/enemy/EnemyTank.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerFlameThrower.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerMachineGun.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerRifle.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerRocketLauncher.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerSniper.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerTank.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerTurret.java
core/src/com/eric/mtd/game/model/actor/support/Apache.java
core/src/com/eric/mtd/game/service/actorfactory/ActorFactory.java
core/src/com/eric/mtd/game/ui/view/EnlistView.java
core/src/com/eric/mtd/util/AudioUtil.java
core/src/com/eric/mtd/util/Logger.java

MTD-36- Improved Enemy AI

---

core/src/com/eric/mtd/game/model/actor/health/HealthBar.java

Changed Health Bars to Pixmaps

MTD - 39 - Changed Health Bars to Pixmaps

---

core/src/com/eric/mtd/game/GameStage.java
core/src/com/eric/mtd/game/model/Player.java
core/src/com/eric/mtd/game/model/level/DynamicWaveGenerator.java
core/src/com/eric/mtd/game/model/level/Level.java
core/src/com/eric/mtd/game/model/level/SpawningEnemy.java
core/src/com/eric/mtd/util/Resources.java
desktop/src/com/eric/mtd/desktop/DesktopLauncher.java

MTD - 3 - Added Dynamic Waves

---

core/src/com/eric/mtd/game/GameStage.java
core/src/com/eric/mtd/game/ui/view/HUDView.java

Fixed bugs related to the game over screen

MTD-43-Fixed game over bugs

---

core/src/com/eric/mtd/MTDGame.java
core/src/com/eric/mtd/game/GameStage.java
core/src/com/eric/mtd/game/helper/Damage.java
core/src/com/eric/mtd/game/model/Player.java
core/src/com/eric/mtd/game/model/actor/combat/CombatActor.java
core/src/com/eric/mtd/game/model/actor/combat/tower/TowerRocketLauncher.java
core/src/com/eric/mtd/game/model/level/DynamicWaveGenerator.java
core/src/com/eric/mtd/game/model/level/Level.java
core/src/com/eric/mtd/game/model/level/state/LevelStateManager.java
core/src/com/eric/mtd/game/ui/presenter/HUDPresenter.java
core/src/com/eric/mtd/game/ui/presenter/InspectPresenter.java
core/src/com/eric/mtd/game/ui/state/GameUIStateManager.java

MTD - 46 - Moved wave loading code

---

android/res/values/strings.xml

MTD - 47- Added Error Message

---

core/src/com/foxholedefense/game/ui/presenter/OptionsPresenter.java
core/src/com/foxholedefense/game/ui/view/OptionsView.java
core/src/com/foxholedefense/util/Resources.java

FHD - 57 - Added speed slider

---

core/src/com/foxholedefense/game/model/actor/projectile/AirStrikeBomb.java
core/src/com/foxholedefense/game/model/actor/projectile/Bullet.java
core/src/com/foxholedefense/game/model/actor/projectile/Explosion.java
core/src/com/foxholedefense/game/model/actor/projectile/RPG.java

FHD - 62 - fixed projectile placement

FHD - 62 - fixed projectile placement

---

core/src/com/foxholedefense/game/GameStage.java
core/src/com/foxholedefense/game/MapRenderer.java
core/src/com/foxholedefense/game/model/level/Map.java

FHD - 67 - Created MapRenderer

FHD - 67 - Created MapRenderer

---

core/src/com/foxholedefense/game/model/actor/combat/tower/TowerFlameThrower.java
core/src/com/foxholedefense/game/model/actor/projectile/Flame.java

FHD - 70 - Fixed flame size

---

.gitignore
android/AndroidManifest.xml
android/build.gradle
android/src/com/foxholedefense/android/FHDApplicationLauncher.java

160 - fixed acra

---

core/src/com/foxholedefense/game/model/Player.java
core/src/com/foxholedefense/game/model/actor/combat/CombatActor.java
core/src/com/foxholedefense/game/model/actor/combat/enemy/Enemy.java
core/src/com/foxholedefense/game/model/actor/combat/tower/Tower.java
core/src/com/foxholedefense/game/model/level/state/LevelStateManager.java
core/src/com/foxholedefense/game/ui/state/GameUIStateManager.java
core/src/com/foxholedefense/state/GameStateManager.java

162 - fixed observer notification

162 - fixed observer notification

---

core/src/com/foxholedefense/game/model/actor/combat/enemy/Enemy.java
core/src/com/foxholedefense/game/model/actor/combat/enemy/EnemyFlameThrower.java
core/src/com/foxholedefense/game/model/actor/combat/tower/TowerFlameThrower.java
core/src/com/foxholedefense/game/model/actor/projectile/Flame.java

191 - improved flame and flame thrower damage

191 - improved flame and flame thrower damage

---

core/src/com/foxholedefense/game/ui/view/GameOverView.java
core/src/com/foxholedefense/game/ui/view/LevelCompletedView.java
core/src/com/foxholedefense/game/ui/view/QuitView.java

238 - added new GUI
